apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nrKubernetesOtel.deployment.configMap.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  gateway-config.yaml: |
    reserved_melt_attributes:
      Metric:
        - interval.ms
        - metricName
  deployment-config.yaml: |
    {{- with include "nrKubernetesOtel.deployment.configMap.config" . }}
    {{- . | nindent 4 }}
    {{- else if .Values.generated }}
    {{- .Values.generated | nindent 4 }}
    {{- else }}
    # Default configuration - please provide configuration via Values.generated
    extensions:
      healthcheckv2:
        use_v2: true
        http:
          endpoint: ${env:MY_POD_IP}:{{ .Values.ports.healthHttp }}
          status:
            enabled: true
            path: "/health/status"
    service:
      extensions: [healthcheckv2]
    {{- end }}